#!/bin/bash

rm -rf ./site/*

tiddlywiki . --build

mv ./output/* ./site/wiki

tiddlywiki wikipath --rendertiddlers '[!is[system]]' $:/core/templates/static.tiddler.html static text/plain
tiddlywiki wikipath --rendertiddler $:/core/templates/static.template.html static.html text/plain
tiddlywiki wikipath --rendertiddler $:/core/templates/static.template.css static/static.css text/plain

mv ./output/static/* ./site

echo "hardwarepunk.com" > ./site/CNAME
