#!/bin/bash

rm -rf ./site/*

tiddlywiki . --build

mv ./output/* ./site/wiki

tiddlywiki --rendertiddlers [!is[system]] 
$:/core/templates/static.tiddler.html static text/plain --rendertiddler 
$:/core/templates/static.template.css static/static.css text/plain

mv ./output/* ./site

echo "hardwarepunk.com" > ./site/CNAME
