#!/bin/bash

rm -rf ./site/*

tiddlywiki . --build

rm ./output/static/index.html
rm ./output/static/*.jpg.html
mv ./output/static/* ./site
mv ./output/* ./site

echo "hardwarepunk.com" > ./site/CNAME
